pipeline:
  core:
    image: lowet84/aspnetcore-builder
    commands:
      - sh publish.sh GraphQlRethinkDbCore $API_KEY
      - sh publish.sh GraphQlRethinkDbLibrary $API_KEY
      - sh publish.sh GraphQlRethinkDbHttp $API_KEY
    secrets: [ api_key ]