pipeline:
  core:
    image: lowet84/aspnetcore-builder
    commands:
      - nuget setApiKey $API_KEY
      - sh publish.sh GraphQlRethinkDbCore
      - sh publish.sh GraphQlRethinkDbLibrary
      - sh publish.sh GraphQlRethinkDbHttp